name: Build and push Docker image

on:
  push:
    branches: [master]

jobs:
  versioning:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      version: ${{ steps.calculate-version.outputs.version-string }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Calculate version
        id: calculate-version
        uses: bitshifted/git-auto-semver@v2.0.11
        with:
          create_tag: true
          initial_version: 1.0.0

  build:
    needs: versioning
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ needs.versioning.outputs.version }}
          build-args: APP_VERSION=${{ needs.versioning.outputs.version }}
